-- 하나금속 제안관리 V1 / Supabase 초기 설정
-- Supabase Dashboard > SQL Editor에서 전체 실행하세요.

create extension if not exists pgcrypto;

create table if not exists public.employees (
  id uuid primary key default gen_random_uuid(),
  employee_no text,
  name text not null,
  department text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, department)
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.proposal_counters (
  year integer primary key,
  last_no integer not null default 0
);

create table if not exists public.proposals (
  id uuid primary key default gen_random_uuid(),
  proposal_no text not null unique,
  received_date date not null default current_date,
  category text not null check (category in ('개선', '안전')),
  proposer_name text not null,
  department text not null,
  title text not null,
  current_problem text not null,
  improvement_plan text not null,
  expected_effect text not null,
  cost_amount bigint not null default 0 check (cost_amount >= 0),
  before_images jsonb not null default '[]'::jsonb,
  after_images jsonb not null default '[]'::jsonb,
  edit_pin_hash text not null,
  status text not null default '접수'
    check (status in ('접수', '심사중', '심사완료')),
  review_result text not null default '미심사'
    check (review_result in ('미심사', '채택', '미채택', '보류', '중복제안', '건수처리')),
  implementing_department text,
  implementation_status text not null default '미실시'
    check (implementation_status in ('미실시', '진행중', '완료')),
  implemented_date date,
  score integer check (score between 0 and 100),
  award_grade text,
  award_amount bigint not null default 0 check (award_amount >= 0),
  payment_status text not null default '미지급'
    check (payment_status in ('미지급', '예정', '완료')),
  effect_amount bigint not null default 0 check (effect_amount >= 0),
  review_comment text,
  reviewer_id uuid references auth.users(id),
  locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.proposal_audit_log (
  id bigint generated by default as identity primary key,
  proposal_id uuid,
  proposal_no text not null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  actor_id uuid,
  actor_type text not null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists proposals_received_date_idx
  on public.proposals(received_date desc);
create index if not exists proposals_department_idx
  on public.proposals(department);
create index if not exists proposals_review_result_idx
  on public.proposals(review_result);
create index if not exists proposals_search_idx
  on public.proposals
  using gin (
    to_tsvector(
      'simple',
      coalesce(proposal_no,'') || ' ' ||
      coalesce(proposer_name,'') || ' ' ||
      coalesce(department,'') || ' ' ||
      coalesce(title,'') || ' ' ||
      coalesce(current_problem,'') || ' ' ||
      coalesce(improvement_plan,'') || ' ' ||
      coalesce(expected_effect,'')
    )
  );

-- 공개 화면 전용 View: 수정번호 해시와 관리자 사용자 ID는 절대 노출하지 않습니다.
create or replace view public.proposal_public as
select
  id,
  proposal_no,
  received_date,
  category,
  proposer_name,
  department,
  title,
  current_problem,
  improvement_plan,
  expected_effect,
  cost_amount,
  before_images,
  after_images,
  status,
  review_result,
  implementing_department,
  implementation_status,
  implemented_date,
  score,
  award_grade,
  award_amount,
  payment_status,
  effect_amount,
  review_comment,
  locked,
  created_at,
  updated_at
from public.proposals;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins
    where user_id = auth.uid()
  );
$$;

create or replace function public.next_proposal_no()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  y integer := extract(year from current_date)::integer;
  n integer;
begin
  insert into public.proposal_counters(year, last_no)
  values (y, 1)
  on conflict (year)
  do update
    set last_no = public.proposal_counters.last_no + 1
  returning last_no into n;

  return 'Q' || right(y::text, 2) || '-' || lpad(n::text, 3, '0');
end;
$$;

create or replace function public.create_proposal(
  p_payload jsonb,
  p_edit_pin text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  created public.proposals;
  next_implementation_status text;
  next_implemented_date date;
begin
  if p_edit_pin !~ '^[0-9]{4}$' then
    raise exception '수정번호는 숫자 4자리여야 합니다.';
  end if;

  if nullif(trim(p_payload->>'proposer_name'), '') is null
     or nullif(trim(p_payload->>'department'), '') is null
     or nullif(trim(p_payload->>'title'), '') is null
     or nullif(trim(p_payload->>'current_problem'), '') is null
     or nullif(trim(p_payload->>'improvement_plan'), '') is null
     or nullif(trim(p_payload->>'expected_effect'), '') is null then
    raise exception '필수 제안 항목이 누락되었습니다.';
  end if;

  if not exists (
    select 1
    from public.employees
    where name = trim(p_payload->>'proposer_name')
      and department = trim(p_payload->>'department')
      and active = true
  ) then
    raise exception '활성 직원명단에서 제안자를 찾지 못했습니다.';
  end if;

  next_implementation_status := coalesce(
    nullif(trim(p_payload->>'implementation_status'), ''),
    '미실시'
  );

  if next_implementation_status not in ('미실시', '진행중', '완료') then
    raise exception '실시상태를 다시 선택하세요.';
  end if;

  if next_implementation_status = '완료' then
    if nullif(trim(p_payload->>'implemented_date'), '') is null then
      raise exception '완료 상태는 실시일을 입력하세요.';
    end if;
    next_implemented_date := (p_payload->>'implemented_date')::date;
  else
    next_implemented_date := null;
  end if;

  insert into public.proposals (
    proposal_no,
    received_date,
    category,
    proposer_name,
    department,
    title,
    current_problem,
    improvement_plan,
    expected_effect,
    cost_amount,
    before_images,
    after_images,
    edit_pin_hash,
    implementation_status,
    implemented_date
  )
  values (
    public.next_proposal_no(),
    current_date,
    p_payload->>'category',
    trim(p_payload->>'proposer_name'),
    trim(p_payload->>'department'),
    trim(p_payload->>'title'),
    trim(p_payload->>'current_problem'),
    trim(p_payload->>'improvement_plan'),
    trim(p_payload->>'expected_effect'),
    coalesce((nullif(p_payload->>'cost_amount', ''))::bigint, 0),
    coalesce(p_payload->'before_images', '[]'::jsonb),
    coalesce(p_payload->'after_images', '[]'::jsonb),
    encode(digest(p_edit_pin, 'sha256'), 'hex'),
    next_implementation_status,
    next_implemented_date
  )
  returning * into created;

  return to_jsonb(created) - 'edit_pin_hash' - 'reviewer_id';
end;
$$;

create or replace function public.edit_proposal_with_pin(
  p_proposal_no text,
  p_edit_pin text,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.proposals;
  updated_row public.proposals;
  next_name text;
  next_department text;
  next_implementation_status text;
  next_implemented_date date;
begin
  select *
  into current_row
  from public.proposals
  where proposal_no = p_proposal_no
  for update;

  if not found then
    raise exception '접수번호를 찾지 못했습니다.';
  end if;

  if current_row.locked or current_row.status in ('심사중', '심사완료') then
    raise exception '관리자가 심사를 시작하여 수정이 잠겼습니다.';
  end if;

  if current_row.edit_pin_hash <> encode(digest(p_edit_pin, 'sha256'), 'hex') then
    raise exception '수정번호가 일치하지 않습니다.';
  end if;

  next_name := coalesce(nullif(trim(p_payload->>'proposer_name'), ''), current_row.proposer_name);
  next_department := coalesce(nullif(trim(p_payload->>'department'), ''), current_row.department);

  if not exists (
    select 1
    from public.employees
    where name = next_name
      and department = next_department
      and active = true
  ) then
    raise exception '활성 직원명단에서 제안자를 찾지 못했습니다.';
  end if;

  if p_payload ? 'implementation_status' then
    next_implementation_status := nullif(trim(p_payload->>'implementation_status'), '');
  else
    next_implementation_status := current_row.implementation_status;
  end if;

  if next_implementation_status not in ('미실시', '진행중', '완료') then
    raise exception '실시상태를 다시 선택하세요.';
  end if;

  if next_implementation_status = '완료' then
    if p_payload ? 'implemented_date' then
      if nullif(trim(p_payload->>'implemented_date'), '') is null then
        raise exception '완료 상태는 실시일을 입력하세요.';
      end if;
      next_implemented_date := (p_payload->>'implemented_date')::date;
    else
      next_implemented_date := current_row.implemented_date;
      if next_implemented_date is null then
        raise exception '완료 상태는 실시일을 입력하세요.';
      end if;
    end if;
  else
    next_implemented_date := null;
  end if;

  update public.proposals
  set
    category = coalesce(nullif(p_payload->>'category', ''), category),
    proposer_name = next_name,
    department = next_department,
    title = coalesce(nullif(trim(p_payload->>'title'), ''), title),
    current_problem = coalesce(nullif(trim(p_payload->>'current_problem'), ''), current_problem),
    improvement_plan = coalesce(nullif(trim(p_payload->>'improvement_plan'), ''), improvement_plan),
    expected_effect = coalesce(nullif(trim(p_payload->>'expected_effect'), ''), expected_effect),
    cost_amount = coalesce((nullif(p_payload->>'cost_amount', ''))::bigint, cost_amount),
    before_images = case
      when p_payload ? 'before_images' then p_payload->'before_images'
      else before_images
    end,
    after_images = case
      when p_payload ? 'after_images' then p_payload->'after_images'
      else after_images
    end,
    implementation_status = next_implementation_status,
    implemented_date = next_implemented_date,
    updated_at = now()
  where id = current_row.id
  returning * into updated_row;

  return to_jsonb(updated_row) - 'edit_pin_hash' - 'reviewer_id';
end;
$$;

create or replace function public.proposal_before_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at := now();
  new.locked := new.status in ('심사중', '심사완료');

  if auth.uid() is not null and public.is_admin() then
    new.reviewer_id := auth.uid();
  end if;

  return new;
end;
$$;

drop trigger if exists proposals_before_update on public.proposals;
create trigger proposals_before_update
before update on public.proposals
for each row
execute function public.proposal_before_update();

create or replace function public.proposal_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_kind text;
begin
  actor_kind := case
    when auth.uid() is not null and public.is_admin() then 'admin'
    when tg_op = 'INSERT' then 'public_submit'
    else 'public_pin_edit'
  end;

  insert into public.proposal_audit_log (
    proposal_id,
    proposal_no,
    action,
    actor_id,
    actor_type,
    before_data,
    after_data
  )
  values (
    coalesce(new.id, old.id),
    coalesce(new.proposal_no, old.proposal_no),
    tg_op,
    auth.uid(),
    actor_kind,
    case when tg_op in ('UPDATE', 'DELETE')
      then to_jsonb(old) - 'edit_pin_hash'
      else null
    end,
    case when tg_op in ('INSERT', 'UPDATE')
      then to_jsonb(new) - 'edit_pin_hash'
      else null
    end
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

drop trigger if exists proposals_audit on public.proposals;
create trigger proposals_audit
after insert or update or delete on public.proposals
for each row
execute function public.proposal_audit();

alter table public.employees enable row level security;
alter table public.admins enable row level security;
alter table public.proposals enable row level security;
alter table public.proposal_counters enable row level security;
alter table public.proposal_audit_log enable row level security;

drop policy if exists "Public can read active employees" on public.employees;
create policy "Public can read active employees"
on public.employees
for select
to anon, authenticated
using (active = true or public.is_admin());

drop policy if exists "Admins manage employees" on public.employees;
create policy "Admins manage employees"
on public.employees
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Authenticated can read proposal public columns" on public.proposals;
create policy "Authenticated can read proposal public columns"
on public.proposals
for select
to authenticated
using (true);

drop policy if exists "Admins update proposals" on public.proposals;
create policy "Admins update proposals"
on public.proposals
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins delete proposals" on public.proposals;
create policy "Admins delete proposals"
on public.proposals
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Admins can view own admin record" on public.admins;
create policy "Admins can view own admin record"
on public.admins
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Admins can read audit log" on public.proposal_audit_log;
create policy "Admins can read audit log"
on public.proposal_audit_log
for select
to authenticated
using (public.is_admin());

revoke all on table public.proposals from anon, authenticated;
revoke all on table public.proposal_counters from anon, authenticated;
revoke all on table public.proposal_audit_log from anon, authenticated;
revoke all on function public.create_proposal(jsonb, text) from public;
revoke all on function public.edit_proposal_with_pin(text, text, jsonb) from public;
revoke all on function public.next_proposal_no() from public;
revoke all on function public.is_admin() from public;

grant usage on schema public to anon, authenticated;
grant select on public.proposal_public to anon, authenticated;
grant select on public.employees to anon, authenticated;
grant insert, update, delete on public.employees to authenticated;
grant select on public.admins to authenticated;
grant select on public.proposal_audit_log to authenticated;

grant select (
  id,
  proposal_no,
  received_date,
  category,
  proposer_name,
  department,
  title,
  current_problem,
  improvement_plan,
  expected_effect,
  cost_amount,
  before_images,
  after_images,
  status,
  review_result,
  implementing_department,
  implementation_status,
  implemented_date,
  score,
  award_grade,
  award_amount,
  payment_status,
  effect_amount,
  review_comment,
  locked,
  created_at,
  updated_at
) on public.proposals to authenticated;

grant update, delete on public.proposals to authenticated;
grant execute on function public.create_proposal(jsonb, text) to anon, authenticated;
grant execute on function public.edit_proposal_with_pin(text, text, jsonb) to anon, authenticated;
grant execute on function public.is_admin() to authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'proposal-images',
  'proposal-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id)
do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public proposal image uploads" on storage.objects;
create policy "Public proposal image uploads"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id = 'proposal-images'
  and (storage.foldername(name))[1] = 'submissions'
  and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp')
);

drop policy if exists "Admins manage proposal images" on storage.objects;
create policy "Admins manage proposal images"
on storage.objects
for all
to authenticated
using (
  bucket_id = 'proposal-images'
  and public.is_admin()
)
with check (
  bucket_id = 'proposal-images'
  and public.is_admin()
);

-- 관리자 생성 방법
-- 1) Supabase Dashboard > Authentication > Users에서 관리자 이메일 계정을 생성합니다.
-- 2) 아래 이메일을 실제 관리자 이메일로 바꿔 실행합니다.
--
-- insert into public.admins(user_id, display_name)
-- select id, '제안관리자'
-- from auth.users
-- where email = 'admin@company.com'
-- on conflict (user_id)
-- do update set display_name = excluded.display_name;
